# Generated by Django 6.0.6 on 2026-07-06 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
        ("riders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(max_length=32, unique=True, verbose_name="订单号"),
                ),
                ("address_snapshot", models.JSONField(verbose_name="地址快照")),
                ("items_snapshot", models.JSONField(verbose_name="商品快照")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总金额"
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="配送费"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="实付金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("accepted", "已接单"),
                            ("preparing", "准备中"),
                            ("ready", "待取餐"),
                            ("picked", "配送中"),
                            ("delivered", "已送达"),
                            ("finished", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="下单时间"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="接单时间"),
                ),
                (
                    "picked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="取餐时间"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="送达时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchants.merchant",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="riders.rider",
                    ),
                ),
            ],
            options={
                "db_table": "order",
                "ordering": ["-created_at"],
            },
        ),
    ]
