# Generated by Django 6.0.6 on 2026-07-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="prepared_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="出餐完成时间"),
        ),
    ]
