# Generated by Django 6.0.6 on 2026-07-06 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="优惠金额"
                    ),
                ),
                (
                    "min_spend",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="最低消费"
                    ),
                ),
                ("valid_until", models.DateTimeField(verbose_name="有效期至")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "coupon",
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unused", "未使用"),
                            ("used", "已使用"),
                            ("expired", "已过期"),
                        ],
                        default="unused",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="使用时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="领取时间"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promotions.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_coupon",
            },
        ),
    ]
