# Generated by Django 6.0.6 on 2026-07-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="配送费"
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="min_order",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="起送金额"
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="monthly_sales",
            field=models.IntegerField(default=0, verbose_name="月销量"),
        ),
    ]
