# Generated by Django 6.0.6 on 2026-07-06 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("real_name", models.CharField(max_length=50, verbose_name="真实姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="电话")),
                (
                    "station",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="站点"
                    ),
                ),
                (
                    "work_status",
                    models.CharField(
                        choices=[
                            ("offline", "离线"),
                            ("idle", "空闲"),
                            ("busy", "忙碌"),
                            ("delivering", "配送中"),
                        ],
                        default="offline",
                        max_length=20,
                        verbose_name="工作状态",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="余额"
                    ),
                ),
                ("total_orders", models.IntegerField(default=0, verbose_name="总单量")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, default=5.0, max_digits=3, verbose_name="评分"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rider",
            },
        ),
    ]
