# Generated by Django 6.0.6 on 2026-07-06 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="标签"
                    ),
                ),
                ("contact_name", models.CharField(max_length=50, verbose_name="收件人")),
                ("contact_phone", models.CharField(max_length=20, verbose_name="电话")),
                ("address", models.CharField(max_length=200, verbose_name="详细地址")),
                ("is_default", models.BooleanField(default=False, verbose_name="默认")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "address",
            },
        ),
    ]
