# Generated by Django 6.0.6 on 2026-07-06 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="分类名称"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="图标"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
            ],
            options={
                "db_table": "category",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="商品名")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                ("image", models.URLField(blank=True, null=True, verbose_name="图片")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="原价",
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="库存")),
                (
                    "status",
                    models.CharField(
                        choices=[("on", "上架"), ("off", "下架")],
                        default="off",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("sales_count", models.IntegerField(default=0, verbose_name="销量")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, default=5.0, max_digits=3, verbose_name="评分"
                    ),
                ),
                ("specs", models.JSONField(blank=True, null=True, verbose_name="规格")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "product",
            },
        ),
    ]
